### ISSUE TITLE
Bug: Connection is not closing properly when not killing the process

### ISSUE THREAD

**Issue by vincss** [JSPrismarine/JSPrismarine#1707]
**Describe the bug**
When the method shutdown is called by the process is not exited, the socket stays open.

**To Reproduce**
Call the method shutdown but without process.exit. 

**Expected behavior**
Socket is closed.

```
DEBUG SleepingBedrock.close : (): BEGIN
2024-10-29 10:15:11 info: Stopping server§r Server/kill
2024-10-29 10:15:11 info: Saving chunks for level §b'world'/Flat§r
2024-10-29 10:15:12 info: Server stopped, Goodbye!
DEBUG SleepingBedrock.close : (): END

/// 

2024-10-29 10:15:17 info: Starting JSPrismarine server version §ev0.10.0§r for Minecraft: Bedrock Edition 1.21.40 (protocol version §e748§r)
DEBUG SleepingBedrock.init : ():
2024-10-29 10:15:17 info: [BedRock] Starting on 19132
2024-10-29 10:15:17 info: [McJava] Ready for battle
2024-10-29 10:15:17 info: Loaded §b'world'/Flat§r as default world! 
2024-10-29 10:15:17 info: Preparing start region for dimension §b'world'/Flat§r
2024-10-29 10:15:17 info: JSPrismarine is now listening on port §b19132 
DEBUG SleepingBedrock.init : AFTER
2024-10-29 10:15:17 warn: [Main] Caught uncaughtException: "bind EADDRINUSE 0.0.0.0:19132"
```

**Comment by filiphsps** [comment]
Hi! Working on fixing the shutdown stability; can you try it in headless mode to verify? (Eg passing headless true)

**Comment by vincss** [comment]
Hi,
I updated to the 0.11.0

I tried with the headless parameter, and it still keeps the socket running when I try to shutdown .
![{0F6A9A9F-E6DB-4EDD-BAF6-A0CDE4C41C5B}](https://github.com/user-attachments/assets/3997b977-38e0-460f-8581-ee49148abdfc)

The option stayAlive is working, I don't need the workarround for the process.exit.


Also when I remove the workarround for the log issue there is an error :
DEBUG SleepingBedrock.close : (): BEGIN
2024-11-03 08:47:54 info: Stopping server§r Server/kill
2024-11-03 08:47:54 info: Saving chunks for level §b'world'/Flat§r
TypeError: Cannot read properties of null (reading 'log')
    at Logger.info (F:\dev\mcsleepingserverstarter\node_modules\@jsprismarine\logger\dist\logger.cjs.cjs:146:17)
    at Server.shutdown (F:\dev\mcsleepingserverstarter\node_modules\@jsprismarine\prismarine\dist\Server.cjs.cjs:306:24)

**Comment by filiphsps** [comment]
Hi @vincss try the latest release :)

**Comment by vincss** [comment]
Thanks, the logger issue is OK.

But the socket issue is still there. When I call shutdown, the socket is not closed, so the real server cannot start.

**Comment by filiphsps** [comment]
> Thanks, the logger issue is OK.
> 
> But the socket issue is still there. When I call shutdown, the socket is not closed, so the real server cannot start.

Does it throw any error(s)?

Also I should cleanup the `bare` feature, since it seems a bit pointless to have everything from the world manager to ban manager and query manager loading when all you really need is RakNet and the protocol.

**Comment by vincss** [comment]
Hi ! 
It's working with 0.12.0 ! The socket is closing. 🥇 

A strange thing is that the ping stays red.
![{6FC8D662-9BAC-4695-84CA-758B64FC86D8}](https://github.com/user-attachments/assets/70a9b0cf-37fd-4148-8c7d-da27f261b937)

I would be good for me to have only the socket and handle the player connection but if it's working its already an increment. 👍
