### ISSUE TITLE
Bug: Client Cannot Join Server / FILE ENOENT

### ISSUE THREAD

**Issue by NubScript7** [JSPrismarine/JSPrismarine#1796]
**Describe the bug**
Connecting to server with Minecraft (Android) 1.21.43.01 client returns `Disconnected from Server` on client side. Server shows `reason=client disconnect`

**To Reproduce**
1. Have Nodejs `v22.4.1` using Linux
2. Clone repository
3. Start server
4. Connect client to server
5. See error

**Expected behavior**
Client should be able to connect and play.

**Screenshots**
![Screenshot_20241210-201424~2](https://github.com/user-attachments/assets/c3b1c4e7-736a-4f0e-9c7c-8329cae1cc1f)

**Smartphone (please complete the following information):**
 - Device: Infinix X660C (X660C-OP)

**Additional context**
logs in text
```
~/github/JSPrismarine $ pnpm run dev

> jsprismarine@0.0.0 dev /data/data/com.termux/files/home/github/JSPrismarine
> pnpm --filter ./packages/server run dev


> @jsprismarine/server@0.12.0 dev /data/data/com.termux/files/home/github/JSPrismarine/packages/server
> nodemon --delay 0 --quiet --spawn --no-stdin --watch "../**/src/**/*.ts" --ext "ts" --exec "vite-node ./src/Server.ts"

[19:57:37 INFO Server.ts:96:16]: Starting JSPrismarine server version v0.12.0 for Minecraft: Bedrock Edition 1.21.40 (protocol version 748)
[19:57:37 VERBOSE world/GeneratorManager.ts:14:28]: Registered 1 generator(s)!
[19:57:38 VERBOSE network/PacketRegistry.ts:125:14]: Registered 58 of 164 packet(s) (took 197.663 ms)!
[19:57:38 VERBOSE network/PacketRegistry.ts:143:14]: Registered 21 packet handler(s) (took 60.63 ms)!
[19:57:38 VERBOSE item/ItemManager.ts:86:33]: Registered 63 item(s) (took 244.632 ms)!
[19:57:39 VERBOSE block/BlockManager.ts:100:33]: Registered 260 block(s) (took 863.86 ms)!
[19:57:39 VERBOSE command/CommandManager.ts:55:14]: Registered 20 commands(s) (took 86.787 ms)!
[19:57:39 INFO world/WorldManager.ts:147:37]: Loading 'world'/Flat as default world!
[19:57:39 INFO world/World.ts:134:33]: Preparing start region for dimension 'world'/Flat
[19:57:48 VERBOSE world/World.ts:146:33]: (took 8569.471 ms)
[19:57:48 VERBOSE world/WorldManager.ts:151:33]: World 'world'/Flat successfully loaded!
[19:57:48 INFO Server.ts:348:21]: JSPrismarine is now listening on port 19132
[19:58:48 INFO world/World.ts:433:33]: Saving chunks for level 'world'/Flat
[19:58:53 VERBOSE world/World.ts:440:33]: (took 5076.589 ms)!
[20:01:02 VERBOSE ServerSocket.ts:130:21]: Session created for client=192.168.2.103:42975, mtu=1492
[20:01:02 VERBOSE Server.ts:207:25]: New connection handling took 6.158 ms
[20:01:03 ERROR]: Error: ENOENT: no such file or directory, open '/data/data/com.termux/files/home/github/JSPrismarine/jsp/worlds/world/playerdata/4,Alex.json'
    at open (node:internal/fs/promises:639:25)
    at Object.readFile (node:internal/fs/promises:1246:14)
    at World.getPlayerData (/data/data/com.termux/files/home/github/JSPrismarine/packages/prismarine/src/world/World.ts:537:25)
    at Player.enable (/data/data/com.termux/files/home/github/JSPrismarine/packages/prismarine/src/Player.ts:93:28)
    at LoginHandler.handle (/data/data/com.termux/files/home/github/JSPrismarine/packages/prismarine/src/network/handler/LoginHandler.ts:69:9)
    at ServerSocket.<anonymous> (/data/data/com.termux/files/home/github/JSPrismarine/packages/prismarine/src/Server.ts:268:25)
[20:01:03 VERBOSE ServerSocket.ts:137:21]: Closed session for client=192.168.2.103:42975, reason=client disconnect
[20:01:03 INFO Console.ts:140:33]: %multiplayer.player.left
```

**Comment by filiphsps** [comment]
Are you logged in to a Microsoft account? (Looks like we're trying to save userdata using an username instead of their uuid which I *guess* happens if you're not authenticated).
